name: Lint Code

on:
  pull_request:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'  

      - name: Install dependencies
        run: |
          cd src/server
          npm install

      - name: Run ESLint
        id: lint
        run: |
          cd src/server
          eslint_output=$(npx eslint . --max-warnings=0 || echo "Linting failed")
          echo "$eslint_output"
          if [[ "$eslint_output" == *"warning"* ]]; then
            echo "linting issues found"
            exit 1  # Fail the step if warnings are found
          fi

      - name: Post PR comment if lint issues found
        if: steps.lint.outcome == 'failure'  # Only runs if the lint step failed
        uses: actions/github-script@v6
        with:
          script: |
            const pr_number = context.payload.pull_request.number;
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
              body: `Linting issues were detected in this pull request. Please run \`npm run lint:fix\` to resolve the issues before merging.`
            })
